### Classification

In [1]:
### !pip install Xgboost

In [2]:
from sklearn.datasets import make_classification, make_regression
X,y = make_classification(n_samples=1000, n_features=4, n_informative=2, n_redundant=0, random_state=0, shuffle=False)

In [3]:
X.shape

(1000, 4)

In [4]:
y.shape

(1000,)

In [5]:
X, y

(array([[-1.66853167, -1.29901346,  0.2746472 , -0.60362044],
        [-2.9728827 , -1.08878294,  0.70885958,  0.42281857],
        [-0.59614125, -1.37007001, -3.11685659,  0.64445203],
        ...,
        [ 0.91711204,  1.10596645,  0.86766522, -2.25625012],
        [ 0.10027664,  1.45875846, -0.44360274, -0.67002328],
        [ 1.0415229 , -0.01987143,  0.15216419, -1.9405334 ]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33, random_state=42)

In [7]:
from sklearn.ensemble import AdaBoostClassifier , AdaBoostRegressor
from sklearn.ensemble import GradientBoostingClassifier, GradientBoostingRegressor
import xgboost as xb

In [8]:
classifier1 = AdaBoostClassifier()
classifier1.fit(X_train, y_train)

AdaBoostClassifier()

In [9]:
y_pred1=classifier1.predict(X_test)

In [10]:
y_pred1

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,

In [11]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred1))
print(accuracy_score(y_test, y_pred1))
print(classification_report(y_test, y_pred1))

[[153  13]
 [ 12 152]]
0.9242424242424242
              precision    recall  f1-score   support

           0       0.93      0.92      0.92       166
           1       0.92      0.93      0.92       164

    accuracy                           0.92       330
   macro avg       0.92      0.92      0.92       330
weighted avg       0.92      0.92      0.92       330



In [12]:
classifier2 = GradientBoostingClassifier()
classifier2.fit(X_train, y_train)

GradientBoostingClassifier()

In [13]:
y_pred2 = classifier2.predict(X_test)

In [14]:
y_pred2

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,

In [15]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred2))
print(accuracy_score(y_test, y_pred2))
print(classification_report(y_test, y_pred2))

[[153  13]
 [  7 157]]
0.9393939393939394
              precision    recall  f1-score   support

           0       0.96      0.92      0.94       166
           1       0.92      0.96      0.94       164

    accuracy                           0.94       330
   macro avg       0.94      0.94      0.94       330
weighted avg       0.94      0.94      0.94       330



In [16]:
classifier3 = xb.XGBClassifier()
classifier3.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [17]:
y_pred3 = classifier3.predict(X_test)

In [18]:
y_pred3

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,

In [19]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred2))
print(accuracy_score(y_test, y_pred2))
print(classification_report(y_test, y_pred2))

[[153  13]
 [  7 157]]
0.9393939393939394
              precision    recall  f1-score   support

           0       0.96      0.92      0.94       166
           1       0.92      0.96      0.94       164

    accuracy                           0.94       330
   macro avg       0.94      0.94      0.94       330
weighted avg       0.94      0.94      0.94       330



### Regression

In [20]:
X,y = make_regression(n_features=4, n_informative=2,  random_state=0, shuffle=False)

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33, random_state=42)

In [22]:
reg1 = AdaBoostRegressor()
reg1.fit(X_train, y_train)

AdaBoostRegressor()

In [23]:
y_predr1 = reg1.predict(X_test)

In [24]:
y_predr1

array([-10.70809655,  -5.99837372,  35.46519187, -50.42753296,
       -41.5731629 ,  -6.49762834,  29.95728791, -37.17057326,
       -57.1887342 ,  40.60808519,  -6.49762834, -32.78040729,
        -4.51743654, -10.39143091,   8.24865435,   8.24865435,
       -10.70809655,   8.24749005, -24.82300441, -12.17552291,
       -29.4690717 ,  -4.62872307,  29.88418279,  32.58933777,
         7.20252016, -28.10218993,  41.61538124, -50.86926721,
        73.70977637,  47.41788   , -33.43456925,  38.75109395,
        -5.46196812])

In [25]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np
mse = mean_squared_error(y_test, y_predr1)
mae = mean_absolute_error(y_test, y_predr1)
rmse = np.sqrt(mse)
print(mse, mae, rmse)
print(r2_score(y_test, y_predr1))

83.38657048221557 7.674641890983235 9.131624744929873
0.9329322676706479


In [26]:
reg2 = GradientBoostingRegressor()
reg2.fit(X_train, y_train)

GradientBoostingRegressor()

In [27]:
y_predr2 = reg2.predict(X_test)

In [28]:
y_predr2

array([-12.97093263,  -4.00974573,  36.16700842, -56.76066705,
       -42.86836018,  -8.95401767,  34.80537303, -43.40207728,
       -63.71279467,  47.39425229,  -9.8456396 , -25.42149148,
        -2.21773065, -18.48501209,  11.90428726,  15.90038256,
       -16.49926193,  11.19154624, -28.04066203, -19.91256638,
       -30.36728095,  -2.80513266,  38.94952376,  32.57538267,
         5.11745391, -28.03335795,  50.33101728, -54.41941772,
        82.24231011,  37.07614671, -38.37488465,  38.25028035,
        -2.71992661])

In [29]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np
mse = mean_squared_error(y_test, y_predr2)
mae = mean_absolute_error(y_test, y_predr2)
rmse = np.sqrt(mse)
print(mse, mae, rmse)
print(r2_score(y_test, y_predr2))

75.64379503046936 6.56404089155328 8.69734413660109
0.9391597739523068


In [30]:
reg3 = xb.XGBRFRegressor()
reg3.fit(X_train, y_train)

XGBRFRegressor(base_score=None, booster=None, callbacks=None,
               colsample_bylevel=None, colsample_bytree=None, device=None,
               early_stopping_rounds=None, enable_categorical=False,
               eval_metric=None, feature_types=None, gamma=None,
               grow_policy=None, importance_type=None,
               interaction_constraints=None, max_bin=None,
               max_cat_threshold=None, max_cat_to_onehot=None,
               max_delta_step=None, max_depth=None, max_leaves=None,
               min_child_weight=None, missing=nan, monotone_constraints=None,
               multi_strategy=None, n_estimators=None, n_jobs=None,
               num_parallel_tree=None, objective='reg:squarederror',
               random_state=None, reg_alpha=None, ...)

In [31]:
y_predr3 = reg3.predict(X_test)

In [32]:
y_predr3

array([-10.728757 ,  -5.156193 ,  40.0032   , -49.740673 , -43.779945 ,
        -6.991785 ,  39.049126 , -42.954227 , -60.156536 ,  45.275826 ,
        -6.551468 , -14.91733  ,  -4.001849 , -16.851093 ,  12.390436 ,
        18.950455 , -12.641865 ,   9.400592 , -24.819553 , -16.072521 ,
       -30.827038 ,  -5.8089657,  40.93766  ,  32.772976 ,   9.678375 ,
       -26.175894 ,  50.74609  , -41.597076 ,  77.67562  ,  56.33236  ,
       -36.073387 ,  47.200687 ,  -5.371067 ], dtype=float32)

In [33]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np
mse = mean_squared_error(y_test, y_predr3)
mae = mean_absolute_error(y_test, y_predr3)
rmse = np.sqrt(mse)
print(mse, mae, rmse)
print(r2_score(y_test, y_predr3))

88.93524999559054 7.506836738929812 9.43054876428676
0.928469470481216
